import AppKit
import Foundation
import CryptoKit
import ImageIO
import UniformTypeIdentifiers
import FloatingMacroCore
// libwebp (BSD-3-clause). macOS's ImageIO does not support WebP encoding, so...
// Call official C libraries directly via SwiftPM.
import libwebp

/// Phase 5: Icons and thumbnail images required from the web panel are resized to the necessary size.
/// Resize and return a PNG encoder renderer after converting to in-memory cache.
/// attached
///
/// Why Necessary:
/// There is a case where a thumbnail of the button specifies a 1456x816 live PNG (2.4MB).
/// If you just transmit via LAN, it will be painfully slow to load on a smartphone.
/// The `IconLoader.image(for:)` caches images at the NSImage level, but does not cache them at the image data level.
/// Each time `pngData(_:)` is called, it goes through an NSBitmapImageRep to create a PNG.
/// Re-encoded.
///
/// Design:
/// Cache key = `(ref, maxSize)` pair. Same icon for 128px and 512px.
/// Hold in separate cache entries.
/// Encode is fixed to PNG (for transparency preservation). JPEG is not adopted because alpha is lost.
/// LRU-like simple limit management (discard from oldest when over 256 entries).
/// ETag is generated by taking the first 16 hex characters of the SHA-256 hash and used in the HTTP If-None-Match path.
/// use.
final class WebPanelIconRenderer: @unchecked Sendable {

    static let shared = WebPanelIconRenderer()

    struct Entry {
        let data: Data
        let etag: String
        let contentType: String
    }

    /// Output format.
    /// png: alpha preserved. Icon use (lossless WebP not available environment).
    /// jpeg: alpha drops, volume 1/5 to 1/10. Thumbnail (photo-like) used.
    /// webp: Supported in iOS 14+ Safari. About 25-35% smaller than same-quality JPEG.
    /// Alpha can maintain, so there is no white background issue for icons.
    enum Format: String {
        case png
        case jpeg
        case webp

        var contentType: String {
            switch self {
            case .png:  return "image/png"
            case .jpeg: return "image/jpeg"
            case .webp: return "image/webp"
            }
        }
    }

    private let lock = NSLock()
    /// Encoded byte sequence cache keyed by `(maxSize, format, ref)`.
    private var cache: [String: Entry] = [:]
    /// Simple LRU insertion order (old to new). Discard the head when capacity is exceeded.
    private var insertionOrder: [String] = []
    private let capacity = 512

    /// Resize `ref` to below `maxSize`, encode it in the specified format, and return an Entry.
    /// When `ref` cannot be resolved, it is nil.
    func render(ref: String, maxSize: Int, format: Format = .png) -> Entry? {
        let key = cacheKey(ref: ref, maxSize: maxSize, format: format)

        lock.lock()
        if let hit = cache[key] {
            lock.unlock()
            return hit
        }
        lock.unlock()

        guard let image = IconLoader.image(for: ref) else { return nil }
        guard let bytes = encodeResized(image: image,
                                        maxSize: CGFloat(maxSize),
                                        format: format) else { return nil }
        let etag = etagFor(bytes)
        let entry = Entry(data: bytes, etag: etag, contentType: format.contentType)

        lock.lock()
        cache[key] = entry
        insertionOrder.append(key)
        if insertionOrder.count > capacity {
            let drop = insertionOrder.removeFirst()
            cache.removeValue(forKey: drop)
        }
        lock.unlock()
        return entry
    }

    /// Encode only the single preset ahead of time for HTML delivery timing.
    /// Called when you realize that the iPhone will see this preset.
    /// Finishes faster than a full scan, so no unnecessary encoding.
    func prewarm(preset: Preset) {
        var iconRefs: Set<String> = []
        var thumbRefs: Set<String> = []
        for group in preset.groups {
            for btn in group.buttons {
                if let i = btn.icon, !i.isEmpty { iconRefs.insert(i) }
                // Launch the action also makes the target an image reference source.
                if case .launch(let target) = btn.action, !target.isEmpty {
                    iconRefs.insert(target)
                }
            }
        }
        prewarmRefs(iconRefs: iconRefs, thumbRefs: thumbRefs)
    }

    /// Encode the icons and thumbnails of all preset buttons in advance
    /// Cache it. Call immediately after turning on LAN public mode to do this.
    /// Reduce concurrent requests during the first iPhone connection.
    ///
    /// Performance considerations:
    /// Convert one thumbnail (1456x816) to a 384px JPEG in a few hundred milliseconds.
    /// Eats CPU. If 10 are lined up, it can cause a high-load period of just seconds.
    /// Therefore:
    /// QoS is fixed to `.background` (lowest).
    /// Sleep for 30ms to yield to other processes after processing each item.
    /// The size bucket is only for the "type that the client seems to request most"
    /// Compress (icon=64 / thumb=384, assuming iPhone with DPR=2)
    /// Remaining buckets are generated on-demand at the time of the first request (cache miss is)
    /// Only one degree, thereafter HTTP's Cache-Control + ETag will work)
    func prewarm(presetManager: PresetManager) {
        let appConfig = presetManager.appConfig
        let presetNames = Set((appConfig?.panels ?? []).map { $0.presetName })
        var iconRefs: Set<String> = []
        var thumbRefs: Set<String> = []
        for name in presetNames {
            guard let preset = presetManager.preset(named: name) else { continue }
            for group in preset.groups {
                for btn in group.buttons {
                    if let icon = btn.icon, !icon.isEmpty { iconRefs.insert(icon) }
                }
            }
        }
        let iconSnap = iconRefs
        let thumbSnap = thumbRefs
        prewarmRefs(iconRefs: iconSnap, thumbRefs: thumbSnap)
    }

    /// Encode the given set of refs in parallel in the background. Remove duplicates from the same ref.
    /// To prevent launch, de-duplicate in the `inFlight` set for HTML delivery with preset
    /// Prewarm is called, but the second time does nothing).
    private func prewarmRefs(iconRefs: Set<String>, thumbRefs: Set<String>) {
        // Which of the refs is currently in-flight to record under a lock and skip?
        lock.lock()
        let icons  = iconRefs.subtracting(prewarmInFlight)
        let thumbs = thumbRefs.subtracting(prewarmInFlight)
        prewarmInFlight.formUnion(icons)
        prewarmInFlight.formUnion(thumbs)
        lock.unlock()

        guard !icons.isEmpty || !thumbs.isEmpty else { return }

        // Parallel encoding with TaskGroup. Utilize M4's 8-10 cores to complete in a few hundred milliseconds.
        // Heavy processing but limited to a few seconds during LAN exposure, so give full power within the range that does not compress main.
        Task.detached(priority: .utility) { [weak self] in
            guard let self else { return }
            await withTaskGroup(of: Void.self) { group in
                for ref in icons {
                    group.addTask { _ = self.render(ref: ref, maxSize: 64, format: .webp) }
                }
                for ref in thumbs {
                    group.addTask { _ = self.render(ref: ref, maxSize: 384, format: .webp) }
                }
            }
            self.lock.lock()
            self.prewarmInFlight.subtract(icons)
            self.prewarmInFlight.subtract(thumbs)
            self.lock.unlock()
            LoggerContext.shared.info("WebPanelIconRenderer", "prewarm complete", [
                "icons":  String(icons.count),
                "thumbs": String(thumbs.count),
            ])
        }
    }

    /// A set to prevent double warming up the same reference. Multiple paths for `prewarm`.
    /// (LAN ON / HTML Streaming / Toggle Switch) Calling it from here still consolidates to essentially one instance.
    private var prewarmInFlight: Set<String> = []

    /// Call when you need to discard the cache after preset editing, etc.
    func invalidate() {
        lock.lock()
        cache.removeAll()
        insertionOrder.removeAll()
        lock.unlock()
    }

    // MARK: - Internal

    private func cacheKey(ref: String, maxSize: Int, format: Format) -> String {
        return "\(format.rawValue):\(maxSize):\(ref)"
    }

    /// Resize NSImage to maxSize or less and encode with format.
    ///
    /// NSImage.lockFocus + draw base implementation is for Retina displays with backing
    /// applied internally with a scale of 2x, resulting in twice the pixel size required.
    /// Outputting the translated English text:

Outputting directly using CGImage/CGContext to accurately manipulate pixels.
    /// Set to intended size.
    private func encodeResized(image: NSImage,
                               maxSize: CGFloat,
                               format: Format) -> Data? {
        var rect = NSRect(origin: .zero,
                          size: image.size != .zero ? image.size : NSSize(width: 1, height: 1))
        guard let cg = image.cgImage(forProposedRect: &rect, context: nil, hints: nil) else {
            return nil
        }
        let srcW = cg.width, srcH = cg.height
        guard srcW > 0 && srcH > 0 else { return nil }

        let mx = CGFloat(max(srcW, srcH))
        let scale = min(maxSize / mx, 1.0)
        let outW = Int((CGFloat(srcW) * scale).rounded())
        let outH = Int((CGFloat(srcH) * scale).rounded())
        guard outW > 0 && outH > 0 else { return nil }

        let cs = CGColorSpaceCreateDeviceRGB()
        // Since JPEG does not support an alpha channel, it is drawn using XRGB with noneSkipLast.
        // Draw PNG/WebP using premultipliedLast (RGBA).
        let bitmapInfo: UInt32
        switch format {
        case .png, .webp:
            bitmapInfo = CGImageAlphaInfo.premultipliedLast.rawValue
                       | CGBitmapInfo.byteOrder32Big.rawValue
        case .jpeg:
            bitmapInfo = CGImageAlphaInfo.noneSkipLast.rawValue
                       | CGBitmapInfo.byteOrder32Big.rawValue
        }
        guard let ctx = CGContext(data: nil,
                                  width: outW, height: outH,
                                  bitsPerComponent: 8,
                                  bytesPerRow: 0,
                                  space: cs,
                                  bitmapInfo: bitmapInfo) else {
            return nil
        }
        if format == .jpeg {
            // Draw white first to ensure pixels don't leak from transparent to black.
            ctx.setFillColor(CGColor(gray: 1.0, alpha: 1.0))
            ctx.fill(CGRect(x: 0, y: 0, width: outW, height: outH))
        }
        ctx.interpolationQuality = .high
        ctx.draw(cg, in: CGRect(x: 0, y: 0, width: outW, height: outH))
        guard let resized = ctx.makeImage() else { return nil }

        switch format {
        case .png:
            let rep = NSBitmapImageRep(cgImage: resized)
            return rep.representation(using: .png, properties: [:])
        case .jpeg:
            let rep = NSBitmapImageRep(cgImage: resized)
            // Snapshot-like thumbnail quality and volume balance is a standard.
            return rep.representation(using: .jpeg,
                                      properties: [.compressionFactor: 0.78])
        case .webp:
            return encodeWebP(resized)
        }
    }

    /// CGImage → WebP bytes via libwebp (`WebPEncodeRGBA`)。
    /// Progress: As of macOS 15.5, ImageIO only supports WebP decode and does not support encoding.
    /// Because `WebP` UTI is not included in (`CGImageDestinationCopyTypeIdentifiers()`).
    /// Link libwebp directly via SwiftPM (SDWebImage/libwebp-Xcode).
    private func encodeWebP(_ image: CGImage, lossless: Bool = false) -> Data? {
        let w = image.width, h = image.height
        guard w > 0 && h > 0 else { return nil }

        // Convert CGImage to RGBA byte sequence. Expand into premultipliedLast CGContext.
        // Draw as (RGBA, alpha tail). WebPEncodeRGBA also expects the same layout.
        let bpr = w * 4
        var rgba = [UInt8](repeating: 0, count: bpr * h)
        let cs = CGColorSpaceCreateDeviceRGB()
        let bitmapInfo: UInt32 = CGImageAlphaInfo.premultipliedLast.rawValue
                               | CGBitmapInfo.byteOrder32Big.rawValue
        guard let ctx = rgba.withUnsafeMutableBytes({ buf -> CGContext? in
            CGContext(data: buf.baseAddress,
                      width: w, height: h,
                      bitsPerComponent: 8,
                      bytesPerRow: bpr,
                      space: cs,
                      bitmapInfo: bitmapInfo)
        }) else {
            return nil
        }
        ctx.draw(image, in: CGRect(x: 0, y: 0, width: w, height: h))

        // Output buffer allocated by libwebp. Freed with WebPFree.
        var out: UnsafeMutablePointer<UInt8>? = nil
        let size: Int = rgba.withUnsafeBufferPointer { buf in
            let base = buf.baseAddress!
            if lossless {
                return WebPEncodeLosslessRGBA(base, Int32(w), Int32(h),
                                              Int32(bpr), &out)
            } else {
                return WebPEncodeRGBA(base, Int32(w), Int32(h),
                                      Int32(bpr), 78.0 /* quality 0–100 */, &out)
            }
        }
        guard size > 0, let out = out else { return nil }
        defer { WebPFree(out) }
        return Data(bytes: out, count: size)
    }

    private func etagFor(_ data: Data) -> String {
        let digest = SHA256.hash(data: data)
        let hex = digest.map { String(format: "%02x", $0) }.joined()
        return "\"" + String(hex.prefix(16)) + "\""
    }
}
